version: 2.1

jobs:
  build_and_push_docker:
    machine: true
    steps:
      - run:
          name: "Login in to docker hub"
          command: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - checkout
      - run:
          name: "Build docker image"
          command: bash ci/build_docker.sh
      - run:
          name: "Push docker images to docker hub"
          command: bash ci/push_docker.sh

workflows:
  main:
    jobs:
      - build_and_push_docker:
          filters:
            branches:
              only:
                - master
